name: jenek_go
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  characters: ^1.3.0
  flutter_svg: ^2.0.7
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
